# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: main.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'main.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmain.proto\x12\x04todo\"8\n\x08TodoItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08\"+\n\x0bTodoRequest\x12\x1c\n\x04item\x18\x01 \x01(\x0b\x32\x0e.todo.TodoItem\"\x14\n\x06TodoId\x12\n\n\x02id\x18\x01 \x01(\t\"=\n\x0cTodoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x1c\n\x04item\x18\x02 \x01(\x0b\x32\x0e.todo.TodoItem\"\x07\n\x05\x45mpty\"1\n\x10TodoListResponse\x12\x1d\n\x05items\x18\x01 \x03(\x0b\x32\x0e.todo.TodoItem2\xd9\x01\n\x0bTodoService\x12\x33\n\nCreateTodo\x12\x11.todo.TodoRequest\x1a\x12.todo.TodoResponse\x12.\n\nDeleteTodo\x12\x0c.todo.TodoId\x1a\x12.todo.TodoResponse\x12\x33\n\nUpdateTodo\x12\x11.todo.TodoRequest\x1a\x12.todo.TodoResponse\x12\x30\n\tListTodos\x12\x0b.todo.Empty\x1a\x16.todo.TodoListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'main_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TODOITEM']._serialized_start=20
  _globals['_TODOITEM']._serialized_end=76
  _globals['_TODOREQUEST']._serialized_start=78
  _globals['_TODOREQUEST']._serialized_end=121
  _globals['_TODOID']._serialized_start=123
  _globals['_TODOID']._serialized_end=143
  _globals['_TODORESPONSE']._serialized_start=145
  _globals['_TODORESPONSE']._serialized_end=206
  _globals['_EMPTY']._serialized_start=208
  _globals['_EMPTY']._serialized_end=215
  _globals['_TODOLISTRESPONSE']._serialized_start=217
  _globals['_TODOLISTRESPONSE']._serialized_end=266
  _globals['_TODOSERVICE']._serialized_start=269
  _globals['_TODOSERVICE']._serialized_end=486
# @@protoc_insertion_point(module_scope)
