version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - "50051:50051"  # Expose server on port 50051 of the host
    volumes:
      - ./Server:/app
    tty: true  # Keep the terminal open
    environment:
      - SERVER_HOST=0.0.0.0  # The server will listen on all interfaces
    networks:
      - petadoption_network

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - ./client:/app
    tty: true  # Keep the terminal open
    environment:
      - SERVER_ADDRESS=server:50051  # Use the correct service name and internal port
    networks:
      - petadoption_network
    depends_on:
      - server  # Ensure client starts after server
    command: >
      bash -c "python test.py && python client.py"  # Run test.py first, then client.py

networks:
  petadoption_network:
    driver: bridge
