# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'services.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\x12\x04todo\"7\n\x11\x43reateToDoRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\" \n\x12\x43reateToDoResponse\x12\n\n\x02id\x18\x01 \x01(\t\"\x1c\n\x0eGetToDoRequest\x12\n\n\x02id\x18\x01 \x01(\t\"A\n\x0fGetToDoResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"C\n\x11UpdateToDoRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"%\n\x12UpdateToDoResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1f\n\x11\x44\x65leteToDoRequest\x12\n\n\x02id\x18\x01 \x01(\t\"%\n\x12\x44\x65leteToDoResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x88\x02\n\x0bToDoService\x12?\n\nCreateToDo\x12\x17.todo.CreateToDoRequest\x1a\x18.todo.CreateToDoResponse\x12\x36\n\x07GetToDo\x12\x14.todo.GetToDoRequest\x1a\x15.todo.GetToDoResponse\x12?\n\nUpdateToDo\x12\x17.todo.UpdateToDoRequest\x1a\x18.todo.UpdateToDoResponse\x12?\n\nDeleteToDo\x12\x17.todo.DeleteToDoRequest\x1a\x18.todo.DeleteToDoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATETODOREQUEST']._serialized_start=24
  _globals['_CREATETODOREQUEST']._serialized_end=79
  _globals['_CREATETODORESPONSE']._serialized_start=81
  _globals['_CREATETODORESPONSE']._serialized_end=113
  _globals['_GETTODOREQUEST']._serialized_start=115
  _globals['_GETTODOREQUEST']._serialized_end=143
  _globals['_GETTODORESPONSE']._serialized_start=145
  _globals['_GETTODORESPONSE']._serialized_end=210
  _globals['_UPDATETODOREQUEST']._serialized_start=212
  _globals['_UPDATETODOREQUEST']._serialized_end=279
  _globals['_UPDATETODORESPONSE']._serialized_start=281
  _globals['_UPDATETODORESPONSE']._serialized_end=318
  _globals['_DELETETODOREQUEST']._serialized_start=320
  _globals['_DELETETODOREQUEST']._serialized_end=351
  _globals['_DELETETODORESPONSE']._serialized_start=353
  _globals['_DELETETODORESPONSE']._serialized_end=390
  _globals['_TODOSERVICE']._serialized_start=393
  _globals['_TODOSERVICE']._serialized_end=657
# @@protoc_insertion_point(module_scope)
