version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - ./Server:/app
    tty: true  # Keep the terminal open
    environment:
      - SERVER_HOST=0.0.0.0  # The server will listen on all interfaces
    networks:
      - petadoption_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50051"]
      interval: 30s
      timeout: 10s
      retries: 5

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      server:
        condition: service_healthy
    volumes:
      - ./client:/app
    tty: true  # Keep the terminal open
    environment:
      - SERVER_ADDRESS=server:50051  # Use service name to connect to the server
    networks:
      - petadoption_network

networks:
  petadoption_network:
    driver: bridge